### ISSUE TITLE
"vagrant sandbox on" on libvirt returns error

### ISSUE THREAD

**Issue by LalatenduMohanty** [jedi4ever/sahara#56]
Steps to reproduce:
- vagrant init centos/7
- vagrant up
- vagrant sandbox on

```
$ vagrant sandbox on
/home/lmohanty/.vagrant.d/gems/gems/sahara-0.0.17/lib/sahara/session/libvirt.rb:1:in `require': cannot load such file -- fog (LoadError)
    from /home/lmohanty/.vagrant.d/gems/gems/sahara-0.0.17/lib/sahara/session/libvirt.rb:1:in `<top (required)>'
    from /home/lmohanty/.vagrant.d/gems/gems/sahara-0.0.17/lib/sahara/session/factory.rb:12:in `require_relative'
    from /home/lmohanty/.vagrant.d/gems/gems/sahara-0.0.17/lib/sahara/session/factory.rb:12:in `create'
    from /home/lmohanty/.vagrant.d/gems/gems/sahara-0.0.17/lib/sahara/command/on.rb:21:in `block in execute'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:235:in `block in with_target_vms'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:229:in `each'
    from /usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:229:in `with_target_vms'
    from /home/lmohanty/.vagrant.d/gems/gems/sahara-0.0.17/lib/sahara/command/on.rb:19:in `execute'
    from /home/lmohanty/.vagrant.d/gems/gems/sahara-0.0.17/lib/sahara/command/root.rb:52:in `execute'
    from /usr/share/vagrant/lib/vagrant/cli.rb:42:in `execute'
    from /usr/share/vagrant/lib/vagrant/environment.rb:302:in `cli'
    from /usr/share/vagrant/bin/vagrant:174:in `<main>'
```

**Comment by vperron** [comment]
Can confirm.

**Comment by ecirtap** [comment]
Me too:
- vagrant 1.8.1
- sahara 0.0.17
- host ubuntu 14.04.4

**Comment by loriezn** [comment]
Me three:

 - vagrant 1.9.4
 - sahara 0.0.17
 - host arch kernal 4.10.13

**Comment by maxlareo** [comment]
Here as well, the issue is still there with :
```
$ uname -a
Linux dmu181 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ vagrant plugin list
sahara (0.0.17)
  - Version Constraint: > 0
vagrant-libvirt (0.0.43)
  - Version Constraint: > 0

$ vagrant -v
Vagrant 2.0.3
```

**Comment by maxlareo** [comment]
Seems like the commit [02f4e5f](https://github.com/jedi4ever/sahara/commit/02f4e5f8ad77867ba1091dfadcca8d4de5ece47b) solve this problem, because by installing the plugin from the sources, it works !

**Comment by swadeley** [comment]
> Seems like the commit [02f4e5f](https://github.com/jedi4ever/sahara/commit/02f4e5f8ad77867ba1091dfadcca8d4de5ece47b) solve this problem, because by installing the plugin from the sources, it works !

Thanks for sharing that. After `vagrant plugin install sahara` I hit this issue.  I edited the file like in the commit then it worked.

I have been told to try 'rvm use system' then sahara again next time.

**Comment by ekeyme** [comment]
> 
> 
> Seems like the commit [02f4e5f](https://github.com/jedi4ever/sahara/commit/02f4e5f8ad77867ba1091dfadcca8d4de5ece47b) solve this problem, because by installing the plugin from the sources, it works !

thx. I works for me.
